# Generated by Django 4.1 on 2022-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="menu",
                to="shops.menu",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="service_site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Shops",
                to="shops.servicesite",
            ),
        ),
    ]
