# Generated by Django 4.1 on 2022-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_alter_shop_menu_alter_shop_service_site"),
    ]

    operations = [
        migrations.DeleteModel(name="Contract",),
        migrations.DeleteModel(name="ContractType",),
    ]
