# Generated by Django 4.1 on 2022-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_delete_contract_delete_contracttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
    ]
