# Generated by Django 4.1 on 2022-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_shop1_drone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop1", name="active", field=models.BooleanField(default=False),
        ),
    ]
