# Generated by Django 4.1 on 2022-09-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_shop1_menu_shop1_service_site"),
    ]

    operations = [
        migrations.DeleteModel(name="Shop1",),
    ]
