# Generated by Django 4.1 on 2022-10-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_shop_drone_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="drone_type",),
    ]
