# Generated by Django 4.1 on 2022-09-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_row_price_orderrow_item_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderrow", name="item_weight",),
    ]
