# Generated by Django 4.1 on 2022-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderrow_item_weight"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="total_price",),
        migrations.RemoveField(model_name="order", name="total_weight",),
    ]
