# Generated by Django 4.1 on 2022-09-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_shop_drone_type"),
        ("orders", "0006_order_lat_location_order_long_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shops.shop"
            ),
        ),
    ]
