# Generated by Django 4.1 on 2022-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", 1),
                    ("Processing", 3),
                    ("Shipped", 4),
                    ("Delievered", 5),
                    ("Closed", 6),
                    ("Canceled", 7),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
